name = "petcarebackend"
main = "worker.js"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]

[vars]
MONGO_URI = "mongodb+srv://POdizo:1234567890@cluster0.zximsxx.mongodb.net/gemini_api?retryWrites=true&w=majority"
SUPABASE_URL = "https://mdlkjdnxgansppoklehv.supabase.co"
SUPABASE_KEY = "sb_publishable_uOuh2g8wKROkfafYLjiYiA_69c0FLOv"
IMAGEKIT_PUBLIC_KEY = "public_/PfWSDFtqlaMUzirk/U1+hFG5IM="
IMAGEKIT_PRIVATE_KEY = "private_QugDN74pUlsdvKYLK3h6aydGtTc="
IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/dios87u67"
