name = "odizo-api"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add environment variables here, e.g., MONGO_URI, PORT, FRONTEND_URL
# Or manage them via Cloudflare Dashboard / Wrangler secrets
